# Team ID mappings for football teams
# This dictionary maps team IDs to team information including names and leagues

TEAM_ID_MAPPING = {
    # Premier League Teams
    "33": {"name": "Manchester United", "league": "Premier League", "country": "England"},
    "34": {"name": "Newcastle United", "league": "Premier League", "country": "England"},
    "35": {"name": "Bournemouth", "league": "Premier League", "country": "England"},
    "36": {"name": "Fulham", "league": "Premier League", "country": "England"},
    "37": {"name": "Brentford", "league": "Premier League", "country": "England"},
    "38": {"name": "Watford", "league": "Premier League", "country": "England"},
    "39": {"name": "Wolves", "league": "Premier League", "country": "England"},
    "40": {"name": "Liverpool", "league": "Premier League", "country": "England"},
    "41": {"name": "Southampton", "league": "Premier League", "country": "England"},
    "42": {"name": "Arsenal", "league": "Premier League", "country": "England"},
    "43": {"name": "Burnley", "league": "Premier League", "country": "England"},
    "44": {"name": "Leicester City", "league": "Premier League", "country": "England"},
    "45": {"name": "Everton", "league": "Premier League", "country": "England"},
    "46": {"name": "Leicester City", "league": "Premier League", "country": "England"},
    "47": {"name": "Tottenham", "league": "Premier League", "country": "England"},
    "48": {"name": "West Ham", "league": "Premier League", "country": "England"},
    "49": {"name": "Chelsea", "league": "Premier League", "country": "England"},
    "50": {"name": "Manchester City", "league": "Premier League", "country": "England"},
    "51": {"name": "Brighton", "league": "Premier League", "country": "England"},
    "52": {"name": "Crystal Palace", "league": "Premier League", "country": "England"},
    "55": {"name": "Brentford", "league": "Premier League", "country": "England"},
    "65": {"name": "Nottingham Forest", "league": "Premier League", "country": "England"},
    "66": {"name": "Aston Villa", "league": "Premier League", "country": "England"},
    
    # La Liga Teams
    "529": {"name": "Barcelona", "league": "La Liga", "country": "Spain"},
    "530": {"name": "Atletico Madrid", "league": "La Liga", "country": "Spain"},
    "531": {"name": "Athletic Bilbao", "league": "La Liga", "country": "Spain"},
    "532": {"name": "Valencia", "league": "La Liga", "country": "Spain"},
    "533": {"name": "Villarreal", "league": "La Liga", "country": "Spain"},
    "534": {"name": "Las Palmas", "league": "La Liga", "country": "Spain"},
    "535": {"name": "Sevilla", "league": "La Liga", "country": "Spain"},
    "536": {"name": "Sevilla", "league": "La Liga", "country": "Spain"},
    "537": {"name": "Real Sociedad", "league": "La Liga", "country": "Spain"},
    "538": {"name": "Celta Vigo", "league": "La Liga", "country": "Spain"},
    "539": {"name": "Levante", "league": "La Liga", "country": "Spain"},
    "540": {"name": "Espanyol", "league": "La Liga", "country": "Spain"},
    "541": {"name": "Real Madrid", "league": "La Liga", "country": "Spain"},
    "542": {"name": "Alaves", "league": "La Liga", "country": "Spain"},
    "543": {"name": "Real Betis", "league": "La Liga", "country": "Spain"},
    "544": {"name": "Getafe", "league": "La Liga", "country": "Spain"},
    "545": {"name": "Rayo Vallecano", "league": "La Liga", "country": "Spain"},
    "546": {"name": "Getafe", "league": "La Liga", "country": "Spain"},
    "547": {"name": "Girona", "league": "La Liga", "country": "Spain"},
    "548": {"name": "Real Valladolid", "league": "La Liga", "country": "Spain"},
    "715": {"name": "Granada", "league": "La Liga", "country": "Spain"},
    
    # Serie A Teams
    "487": {"name": "Lazio", "league": "Serie A", "country": "Italy"},
    "488": {"name": "Spezia", "league": "Serie A", "country": "Italy"},
    "489": {"name": "AC Milan", "league": "Serie A", "country": "Italy"},
    "490": {"name": "Cagliari", "league": "Serie A", "country": "Italy"},
    "491": {"name": "Inter", "league": "Serie A", "country": "Italy"},
    "492": {"name": "Napoli", "league": "Serie A", "country": "Italy"},
    "493": {"name": "Atalanta", "league": "Serie A", "country": "Italy"},
    "494": {"name": "Udinese", "league": "Serie A", "country": "Italy"},
    "495": {"name": "Genoa", "league": "Serie A", "country": "Italy"},
    "496": {"name": "Juventus", "league": "Serie A", "country": "Italy"},
    "497": {"name": "AS Roma", "league": "Serie A", "country": "Italy"},
    "498": {"name": "Fiorentina", "league": "Serie A", "country": "Italy"},
    "499": {"name": "Atalanta", "league": "Serie A", "country": "Italy"},
    "500": {"name": "Bologna", "league": "Serie A", "country": "Italy"},
    "502": {"name": "Fiorentina", "league": "Serie A", "country": "Italy"},
    "503": {"name": "Torino", "league": "Serie A", "country": "Italy"},
    "504": {"name": "Hellas Verona", "league": "Serie A", "country": "Italy"},
    "505": {"name": "Inter", "league": "Serie A", "country": "Italy"},
    "511": {"name": "Sassuolo", "league": "Serie A", "country": "Italy"},
    "514": {"name": "Venezia", "league": "Serie A", "country": "Italy"},
    "515": {"name": "Empoli", "league": "Serie A", "country": "Italy"},
    "867": {"name": "Lecce", "league": "Serie A", "country": "Italy"},
    
    # Bundesliga Teams
    "154": {"name": "Bayern Munich", "league": "Bundesliga", "country": "Germany"},
    "155": {"name": "Borussia Dortmund", "league": "Bundesliga", "country": "Germany"},
    "157": {"name": "Bayer Leverkusen", "league": "Bundesliga", "country": "Germany"},
    "158": {"name": "VfL Wolfsburg", "league": "Bundesliga", "country": "Germany"},
    "159": {"name": "Hertha Berlin", "league": "Bundesliga", "country": "Germany"},
    "160": {"name": "SC Freiburg", "league": "Bundesliga", "country": "Germany"},
    "161": {"name": "VfB Stuttgart", "league": "Bundesliga", "country": "Germany"},
    "162": {"name": "Werder Bremen", "league": "Bundesliga", "country": "Germany"},
    "163": {"name": "Borussia Monchengladbach", "league": "Bundesliga", "country": "Germany"},
    "164": {"name": "FSV Mainz 05", "league": "Bundesliga", "country": "Germany"},
    "165": {"name": "Borussia Dortmund", "league": "Bundesliga", "country": "Germany"},
    "167": {"name": "1899 Hoffenheim", "league": "Bundesliga", "country": "Germany"},
    "168": {"name": "Bayer Leverkusen", "league": "Bundesliga", "country": "Germany"},
    "169": {"name": "Eintracht Frankfurt", "league": "Bundesliga", "country": "Germany"},
    "170": {"name": "FC Augsburg", "league": "Bundesliga", "country": "Germany"},
    "172": {"name": "VfB Stuttgart", "league": "Bundesliga", "country": "Germany"},
    "173": {"name": "RB Leipzig", "league": "Bundesliga", "country": "Germany"},
    "174": {"name": "FC Union Berlin", "league": "Bundesliga", "country": "Germany"},
    "176": {"name": "VfL Bochum", "league": "Bundesliga", "country": "Germany"},
    "182": {"name": "FC Koln", "league": "Bundesliga", "country": "Germany"},
    
    # Ligue 1 Teams
    "77": {"name": "Lille", "league": "Ligue 1", "country": "France"},
    "78": {"name": "Marseille", "league": "Ligue 1", "country": "France"},
    "79": {"name": "Lorient", "league": "Ligue 1", "country": "France"},
    "80": {"name": "Lyon", "league": "Ligue 1", "country": "France"},
    "81": {"name": "Marseille", "league": "Ligue 1", "country": "France"},
    "82": {"name": "Montpellier", "league": "Ligue 1", "country": "France"},
    "83": {"name": "Nantes", "league": "Ligue 1", "country": "France"},
    "84": {"name": "Nice", "league": "Ligue 1", "country": "France"},
    "85": {"name": "Paris Saint Germain", "league": "Ligue 1", "country": "France"},
    "86": {"name": "Rennes", "league": "Ligue 1", "country": "France"},
    "87": {"name": "Strasbourg", "league": "Ligue 1", "country": "France"},
    "88": {"name": "Toulouse", "league": "Ligue 1", "country": "France"},
    "89": {"name": "Troyes", "league": "Ligue 1", "country": "France"},
    "90": {"name": "Angers", "league": "Ligue 1", "country": "France"},
    "91": {"name": "Monaco", "league": "Ligue 1", "country": "France"},
    "92": {"name": "Clermont Foot", "league": "Ligue 1", "country": "France"},
    "93": {"name": "Reims", "league": "Ligue 1", "country": "France"},
    "94": {"name": "Rennes", "league": "Ligue 1", "country": "France"},
    "95": {"name": "Saint Etienne", "league": "Ligue 1", "country": "France"},
    "96": {"name": "Lens", "league": "Ligue 1", "country": "France"},
    "97": {"name": "Brest", "league": "Ligue 1", "country": "France"},
    "98": {"name": "Le Havre", "league": "Ligue 1", "country": "France"},
    
    # Add more teams as needed...
    # This is a basic mapping that can be extended
} 